export const dogRaces = [
  { key: '1', race: "Akita" },
  { key: '2', race: "Basset Hound" },
  { key: '3', race: "Beagle" },
  { key: '4', race: "Bichon Frisé" },
  { key: '5', race: "Boiadeiro Australiano" },
  { key: '6', race: "Border Collie" },
  { key: '7', race: "Boston Terrier" },
  { key: '8', race: "Boxer" },
  { key: '9', race: "Buldogue Francês" },
  { key: '10', race: "Buldogue Inglês" },
  { key: '11', race: "Bull Terrier" },
  { key: '12', race: "Cane Corso" },
  { key: '13', race: "Cavalier King Charlespaniel" },
  { key: '14', race: "Chihuahua" },
  { key: '15', race: "Chow Chow" },
  { key: '16', race: "Cocker Spaniel Inglês" },
  { key: '17', race: "Dachshund" },
  { key: '18', race: "Dálmata" },
  { key: '19', race: "Doberman" },
  { key: '20', race: "Dogo Argentino" },
  { key: '21', race: "Dogue Alemão" },
  { key: '22', race: "Fila Brasileiro" },
  { key: '23', race: "Golden Retriever" },
  { key: '24', race: "Husky Siberiano" },
  { key: '25', race: "Jack Russell" },
  { key: '26', race: "Labrador Retriever" },
  { key: '27', race: "Lhasa Apso" },
  { key: '28', race: "Lulu da Pomerânia" },
  { key: '29', race: "Maltês" },
  { key: '30', race: "Mastiff Inglês" },
  { key: '31', race: "Mastim Tibetano" },
  { key: '32', race: "Pastor Alemão" },
  { key: '33', race: "Pastor Australiano" },
  { key: '34', race: "Pastor de Shetland" },
  { key: '35', race: "Pequinês" },
  { key: '36', race: "Pinscher" },
  { key: '37', race: "Pit Bull" },
  { key: '38', race: "Poodle" },
  { key: '39', race: "Pug" },
  { key: '40', race: "Rottweiler" },
  { key: '41', race: "Schnauzer" },
  { key: '42', race: "Shar-pei" },
  { key: '43', race: "Shiba" },
  { key: '44', race: "Shih Tzu" },
  { key: '45', race: "Staffordshire Bull Terrier" },
  { key: '46', race: "Weimaraner" },
  { key: '47', race: "Yorkshire" },
  { key: '48', race: "Vira-lata" },
];